<?php

declare(strict_types=1);

namespace App\Bridge\InfluxDb;

use App\Entity\Project;
use App\Plan\PlanResolver;
use GuzzleHttp\Psr7\Request;
use InfluxDB2\Client;
use InfluxDB2\Model\Bucket;
use InfluxDB2\Model\BucketRetentionRules;
use InfluxDB2\Model\PatchBucketRequest;
use InfluxDB2\Model\PatchRetentionRule;
use InfluxDB2\Model\PostBucketRequest;
use InfluxDB2\Model\WritePrecision;
use InfluxDB2\QueryApi;
use InfluxDB2\Service\BucketsService;
use InfluxDB2\WriteApi;
use InfluxDB2\WriteType;
use Psr\Http\Client\ClientInterface;
use Psr\Log\LoggerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

class InfluxDb
{
    private Client $influxClient;
    private BucketsService $bucketSevice;
    private WriteApi $writeApi;
    public QueryApi $queryApi;
    private ?string $resolvedOrgId = null;

    public function __construct(
        #[Autowire(env: 'INFLUXDB_URL')]
        private readonly string $url,
        #[Autowire(env: 'INFLUXDB_TOKEN')]
        private readonly string $token,
        #[Autowire(env: 'INFLUXDB_ORG_ID')]
        private readonly string $orgId,
        #[Autowire(env: 'INFLUXDB_ORG_NAME')]
        private readonly string $orgName,
        private readonly LoggerInterface $logger,
        private readonly ClientInterface $httpClient,
        private readonly PlanResolver $planResolver,
    ) {
        $this->influxClient = new Client([
            'url' => $url,
            'token' => $token,
            'debug' => false,
            'org' => $orgName,
            'httpClient' => $httpClient,
            'timeout' => 5,
            'precision' => WritePrecision::S,
        ]);
        $this->bucketSevice = $this->influxClient->createService(BucketsService::class);
        $this->writeApi = $this->influxClient->createWriteApi([
            'writeType' => WriteType::SYNCHRONOUS,
            // 'batchSize'=> ''
        ]);
        $this->queryApi = $this->influxClient->createQueryApi();
    }

    public function createBucketForProject(Project $project): Bucket
    {
        return $this->createBucket(
            name: uniqid(),
            description: $project->getName(),
            retentionDuration: $this->planResolver->resolve($project)->influxDataRetentionSecond(),
        );
    }

    /**
     * Org ID from INFLUXDB_ORG_ID, or resolved once from INFLUXDB_ORG_NAME through the
     * API when the env var is empty. The ID generated by `influx setup` is random, so
     * dev/self-hosted setups cannot commit it as a default — the name is stable instead.
     */
    public function getOrgId(): string
    {
        if ($this->orgId !== '') {
            return $this->orgId;
        }

        if ($this->resolvedOrgId !== null) {
            return $this->resolvedOrgId;
        }

        $request = new Request('GET', rtrim($this->url, '/') . '/api/v2/orgs?org=' . rawurlencode($this->orgName), [
            'Authorization' => 'Token ' . $this->token,
            'Accept' => 'application/json',
        ]);

        $body = (string) $this->httpClient->sendRequest($request)->getBody();
        $id = json_decode($body, true)['orgs'][0]['id'] ?? null;

        if (!is_string($id) || $id === '') {
            throw new \RuntimeException(sprintf('Unable to resolve the InfluxDB org ID for org "%s". Check INFLUXDB_ORG_NAME / INFLUXDB_TOKEN, or set INFLUXDB_ORG_ID explicitly.', $this->orgName));
        }

        return $this->resolvedOrgId = $id;
    }

    public function createBucket(string $name, ?string $description = null, ?int $retentionDuration = null): Bucket
    {
        $rule = new BucketRetentionRules();
        $rule->setEverySeconds($retentionDuration);

        $postBucketRequest = new PostBucketRequest();

        $postBucketRequest
            ->setName($name)
            ->setDescription($description)
            ->setRetentionRules([$rule])
            ->setOrgId($this->getOrgId())
        ;

        $bucket = $this->bucketSevice->postBuckets($postBucketRequest);

        if ($bucket instanceof Bucket) {
            return $bucket;
        }

        $this->logger->error('Error while creating bucket', [
            'name' => $name,
            'description' => $description,
            'retentionDuration' => $retentionDuration,
        ]);

        throw new \RuntimeException('Unable to create bucket');
    }

    /**
     * Updates the retention duration of an existing bucket (e.g. on a plan change).
     */
    public function updateBucketRetention(string $bucketId, int $retentionDuration): void
    {
        $rule = new PatchRetentionRule();
        $rule->setEverySeconds($retentionDuration);

        $patchBucketRequest = new PatchBucketRequest();
        $patchBucketRequest->setRetentionRules([$rule]);

        $this->bucketSevice->patchBucketsID($bucketId, $patchBucketRequest);
    }

    public function deleteBucket(string $bucketId): void
    {
        $this->bucketSevice->deleteBucketsID($bucketId);
    }

    public function writePoints(array $points, string $bucketId): void
    {
        $this->writeApi->write($points, bucket: $bucketId);
    }
}
