# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
framework:
    default_locale: en
    # Listed explicitly so Symfony does not generate unused translation catalogues.
    enabled_locales: [ 'fr', 'en' ]

    translator:
        default_path: '%kernel.project_dir%/translations'
        providers:
        fallbacks: ['en']
