name: Bug report
description: Something in JMonitor is not working as expected
labels: [bug]
body:
    -   type: dropdown
        id: edition
        attributes:
            label: Edition
            options:
                - I don't know / both
                - Cloud (jmonitor.io)
                - Self-hosted
            default: 0

    -   type: textarea
        id: description
        attributes:
            label: Description
        validations:
            required: true
