name: Feature request
description: Suggest a new feature, or an improvement to an existing one
labels: [feature request]
body:
    -   type: dropdown
        id: edition
        attributes:
            label: Edition
            options:
                - I don't know / both
                - Cloud (jmonitor.io)
                - Self-hosted
            default: 0

    -   type: textarea
        id: description
        attributes:
            label: Description
        validations:
            required: true
