[PHP]
expose_php = Off
;upload_max_filesize = 8M
memory_limit = 128M
log_errors = On
max_execution_time = 30

; default 4096K sur clevercloud en tout cas
realpath_cache_size = 8192K
; default 120 sur clevercloud en tout cas
realpath_cache_ttl = 3600

[Date]
date.timezone = Europe/Paris

[opcache]
; default 128
opcache.memory_consumption=96

; default 10000
opcache.max_accelerated_files=20000

; default 1
opcache.validate_timestamps=0

; default R
opcache.preload=config/preload.php
;opcache.preload_user=root

; active apcu pour cache system de SF
[apcu]
apc.enabled=1
apc.shm_segments=1
apc.shm_size=32M
;apc.enable_cli=0
